project_id = "rsdjfnsbimcdrxlhognv"

[functions.accept-invite]
verify_jwt = false

[functions.analyze-message]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.generate-disclosure-export]
verify_jwt = false

[functions.support-form]
verify_jwt = true
